import type { Metadata } from "next";
import "./index.css"
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
          <Header />
    <html lang="en">
      <body className="m-0 p-0 min-h-screen font-sans">
        {children}
      </body>
    </html>
              <Footer />
              </>
  );
}
